const $=s=>document.querySelector(s), api=p=>fetch('/api/v1/'+p).then(r=>r.json());
const money=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(n);
async function load(){const [dash,pos,vendors,docs]=await Promise.all([api('dashboard'),api('pos/pending'),api('vendors'),api('documents')]);let s=dash.stats;$('#stats').innerHTML=[['Total inventory value',money(s.value),'Across '+s.total+' tracked assets'],['Asset deployment mix',s.deployed+' deployed',Math.round(s.deployed/s.total*100)+'% of inventory'],['Active purchase orders',pos.filter(x=>x.status!=='Received').length,'In the approval pipeline'],['Compliance alerts',docs.filter(x=>x.status!=='Verified').length,'Items need attention']].map(x=>`<div class="stat"><p>${x[0]}</p><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');
$('#zones').innerHTML=dash.zones.map(z=>{let c=z.pct>85?'danger':z.pct>=60?'warn':'';return `<div class="zone"><b>Zone ${z.zone}</b><span>${z.occupied}/${z.capacity} bins</span><div class="bar ${c}"><i style="width:${z.pct}%"></i></div></div>`}).join('');
$('#pos').innerHTML=pos.map(p=>`<div class="row"><div><b>${p.po_number}</b><br><small>${p.vendor} · ${money(p.total)}</small></div><span class="tag">${p.status}</span></div>`).join('');
$('#vendors').innerHTML=vendors.map(v=>`<div class="row"><div><b>${v.name}</b><br><small>${v.on_time_rate}% on-time · ${v.defect_rate}% defect rate</small></div><b>★ ${v.rating}</b></div>`).join('');
$('#scans').innerHTML=dash.scans.map(x=>`<div class="row"><div><b>${x.action}</b><br><small>${x.name} · ${x.qr_code}</small></div><small>${new Date(x.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('');
$('#docs').innerHTML=docs.map(d=>`<div class="row"><div><b>${d.document_type}</b><br><small>${d.reference_no} · ${d.owner}</small></div><span class="tag">${d.status}</span></div>`).join('');}
$('#loginForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),r=await fetch('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});if(!r.ok)return alert('Sign-in failed.');$('#login').hidden=true;$('#app').hidden=false;load()};
$('#toggle').onclick=()=>{if(innerWidth<850)$('#sidebar').classList.toggle('open');else $('#sidebar').classList.toggle('collapsed')};$('#profile').onclick=()=>$('#profileMenu').hidden=!$('#profileMenu').hidden;$('#logout').onclick=()=>location.reload();$('#mobileBtn').onclick=()=>$('#scanner').showModal();$('#closeScan').onclick=()=>$('#scanner').close();let action='Inventory Intake';document.querySelectorAll('.modes button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.modes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');action=b.textContent});$('#scanNow').onclick=async()=>{let r=await fetch('/api/v1/assets/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({qr_code:$('#qr').value,action})});let d=await r.json();$('#scanResult').textContent=r.ok?`${d.asset.name} recorded for ${action}.`:d.error;if(r.ok)load()};
